# site title
title: 'Jimus.io的说说'

# user name or organization name
user: 'jimusio'

# issue repository
repository: 'blog'

# multi-author
authors: 'SchumyHao'

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: '6#1f76ac6ee5f2515a9db9598c2deeec81a4e1537'

# posts per page
perpage: 10


# advance config

# organization repository (?)
organization: true

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'UPDATED_AT'
